spring:
  datasource:
    validation-query: SELECT 1 FROM DUAL
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: '50'
      minimum-idle: '20'
    username: root
    password: 1234
    test-on-borrow: 'true'
    url: jdbc:mysql://127.0.0.1:3306/test_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  data:
  # Redis 관련
    redis:
      port: 6379 # Redis 서버 포트
      password: 1234 # Redis 서버의 로그인 비밀번호
      host: 127.0.0.1 # Redis 서버 호스트
  session:
    redis:
      flush-mode: ON_SAVE # 세션 플러시 모드
      namespace: spring:session # 세션을 저장하는 데 사용되는 키의 네임스페이스
    store-type: redis # redis를 Spring Session 저장소로 사용(java단 @EnableRedisHttpSessions 대체)
    timeout: 200 # redis session 사용시 session time(단위는 초)
  security:
    user:
      name: user # test
      password: 1234 # test
logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: ERROR
        security:
          web: DEBUG       
    jdbc:
      resultsettable: DEBUG
      sqlonly: DEBUG
    root: WARN
    com:
      example: DEBUG 
mybatis:
  mapper-locations: classpath*:com/example/**/mapper/*.xml
  configuration:
    jdbcTypeForNull: 'null'          
server:
  port: 9091
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    #session:
      #timeout: 300 # 세션 시간 초과. 기간 접미사를 지정하지 않으면 초가 사용됩니다.(java단에서 @EnableRedisHttpSessions 사용시 여기서 설정한 값이 무시됨, 우선순위 낮은듯함)
           
